"""Initial migration with comprehensive song model and supporting tables

Revision ID: 7b2cb245a0aa
Revises: 
Create Date: 2025-11-17 02:19:22.365946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2cb245a0aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_technique_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_technique_tags_id'), 'class_technique_tags', ['id'], unique=False)
    op.create_index(op.f('ix_class_technique_tags_tag_name'), 'class_technique_tags', ['tag_name'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_id'), 'instruments', ['id'], unique=False)
    op.create_index(op.f('ix_instruments_name'), 'instruments', ['name'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.String(length=255), nullable=False),
    sa.Column('singer', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('released_date', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('time_signature', sa.Integer(), nullable=True),
    sa.Column('lyrics_reappraisal', sa.Float(), nullable=True, comment="Lyric's Reappraisal"),
    sa.Column('lyrics_distracting', sa.Float(), nullable=True, comment="Lyric's Distracting"),
    sa.Column('lyrics_uplifting', sa.Float(), nullable=True, comment="Lyric's Uplifting"),
    sa.Column('lyrics_relaxing', sa.Float(), nullable=True, comment="Lyric's Relaxing"),
    sa.Column('lyrics_suppressing', sa.Float(), nullable=True, comment="Lyric's Suppressing"),
    sa.Column('lyrics_motivational', sa.Float(), nullable=True, comment="Lyric's Motivational"),
    sa.Column('audio_reappraisal', sa.Float(), nullable=True, comment="Audio's Reappraisal"),
    sa.Column('audio_distracting', sa.Float(), nullable=True, comment="Audio's Distracting"),
    sa.Column('audio_uplifting', sa.Float(), nullable=True, comment="Audio's Uplifting"),
    sa.Column('audio_relaxing', sa.Float(), nullable=True, comment="Audio's Relaxing"),
    sa.Column('audio_suppressing', sa.Float(), nullable=True, comment="Audio's Suppressing"),
    sa.Column('audio_motivational', sa.Float(), nullable=True, comment="Audio's Motivational"),
    sa.Column('openness', sa.Float(), nullable=True),
    sa.Column('conscientiousness', sa.Float(), nullable=True),
    sa.Column('extraversion', sa.Float(), nullable=True),
    sa.Column('agreeableness', sa.Float(), nullable=True),
    sa.Column('neuroticism', sa.Float(), nullable=True),
    sa.Column('technique_description', sa.Text(), nullable=True),
    sa.Column('class_technique_tags', sa.JSON(), nullable=True),
    sa.Column('used_instruments', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('spotify_id', sa.String(length=100), nullable=True),
    sa.Column('youtube_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_genre'), 'songs', ['genre'], unique=False)
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_index(op.f('ix_songs_singer'), 'songs', ['singer'], unique=False)
    op.create_index(op.f('ix_songs_song_name'), 'songs', ['song_name'], unique=False)
    op.create_table('techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techniques_id'), 'techniques', ['id'], unique=False)
    op.create_index(op.f('ix_techniques_name'), 'techniques', ['name'], unique=True)
    op.create_table('bandit_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('arm_id', sa.String(length=255), nullable=False),
    sa.Column('pulls', sa.Integer(), nullable=True),
    sa.Column('rewards', sa.Float(), nullable=True),
    sa.Column('avg_reward', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('model_parameters', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_stats_id'), 'bandit_stats', ['id'], unique=False)
    op.create_table('big5_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('openness', sa.Float(), nullable=True),
    sa.Column('conscientiousness', sa.Float(), nullable=True),
    sa.Column('extraversion', sa.Float(), nullable=True),
    sa.Column('agreeableness', sa.Float(), nullable=True),
    sa.Column('neuroticism', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_big5_scores_id'), 'big5_scores', ['id'], unique=False)
    op.create_table('song_instruments',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'instrument_id')
    )
    op.create_table('therapy_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('therapy_type', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('session_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapy_sessions_id'), 'therapy_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_session_id'), 'therapy_sessions', ['session_id'], unique=True)
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_id'), 'user_activity', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_session_id'), 'user_activity', ['session_id'], unique=False)
    op.create_table('therapy_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('song_title', sa.String(length=255), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('arousal', sa.Float(), nullable=True),
    sa.Column('recommendation_score', sa.Float(), nullable=True),
    sa.Column('context_features', sa.Text(), nullable=True),
    sa.Column('algorithm_used', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['therapy_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapy_recommendations_id'), 'therapy_recommendations', ['id'], unique=False)
    op.create_table('therapy_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('feedback_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_comments', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['therapy_recommendations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['therapy_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapy_feedback_id'), 'therapy_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_therapy_feedback_id'), table_name='therapy_feedback')
    op.drop_table('therapy_feedback')
    op.drop_index(op.f('ix_therapy_recommendations_id'), table_name='therapy_recommendations')
    op.drop_table('therapy_recommendations')
    op.drop_index(op.f('ix_user_activity_session_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_id'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_therapy_sessions_session_id'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_id'), table_name='therapy_sessions')
    op.drop_table('therapy_sessions')
    op.drop_table('song_instruments')
    op.drop_index(op.f('ix_big5_scores_id'), table_name='big5_scores')
    op.drop_table('big5_scores')
    op.drop_index(op.f('ix_bandit_stats_id'), table_name='bandit_stats')
    op.drop_table('bandit_stats')
    op.drop_index(op.f('ix_techniques_name'), table_name='techniques')
    op.drop_index(op.f('ix_techniques_id'), table_name='techniques')
    op.drop_table('techniques')
    op.drop_index(op.f('ix_songs_song_name'), table_name='songs')
    op.drop_index(op.f('ix_songs_singer'), table_name='songs')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_genre'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_instruments_name'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_id'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_class_technique_tags_tag_name'), table_name='class_technique_tags')
    op.drop_index(op.f('ix_class_technique_tags_id'), table_name='class_technique_tags')
    op.drop_table('class_technique_tags')
    # ### end Alembic commands ###